vim.cmd [[ colorscheme space-vim-dark ]]
vim.cmd [[ hi Comment cterm=italic ]]
vim.cmd [[ hi Normal ctermbg=NONE guibg=NONE ]]
vim.cmd [[ hi LineNr ctermbg=NONE guibg=NONE ]]
vim.cmd [[ hi SignColumn ctermbg=NONE guibg=NONE ]]
